### ISSUE TITLE
Driver should be updated

### ISSUE THREAD

**Issue by olm52** [bondagit/ravenna-alsa-lkm#14]
From here:
https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/
I see there are some recent updates

**Comment by Matzeee** [comment]
I also overlooked, that branch `aes67-daemon` is way more up to date than `master`.

However, is this commit possibly relevant?
https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/commits/47d8ee010304f3bdff11e4c18ad0ca1a9f4cb5af

**Comment by bondagit** [comment]
Thanks for this info. I am testing this change and if ok I will release a new version of the driver.

**Comment by bondagit** [comment]
no go. I am having platform test failure if I apply this patch.

**Comment by olm52** [comment]
Not compiling with kernel 6.11:

`/var/lib/dkms/ravenna-alsa-lkm/r153.9897287/build/audio_driver.c:2218:19: error: incompatible function pointer types initializing 'void (*)(struct platform_device *)' with an expression of type 'int (struct platform_device *)' [-Wincompatible-function-pointer-types]
 2218 |     .remove     = mr_alsa_audio_chip_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/ravenna-alsa-lkm/r153.9897287/build/audio_driver.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.11.0-1-audiolinux-rt/build/Makefile:1929: /var/lib/dkms/ravenna-alsa-lkm/r153.9897287/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.11.0-1-audiolinux-rt/build'
make: *** [Makefile:15: modules] Error 2
`

**Comment by bondagit** [comment]
> Not compiling with kernel 6.11:
> 
> /var/lib/dkms/ravenna-alsa-lkm/r153.9897287/build/audio_driver.c:2218:19: error: incompatible function pointer types initializing 'void (*)(struct platform_device *)' with an expression of type 'int (struct platform_device *)' [-Wincompatible-function-pointer-types]

See issue#22

**Comment by olm52** [comment]
Not compiling with just released kernel 6.12.0

<pre><code>/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1384:11: error: call to undeclared function 'snd_pcm_lib_alloc_vmalloc_buffer'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1384 |     err = snd_pcm_lib_alloc_vmalloc_buffer(substream, bufferBytes);
      |           ^
/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1411:19: error: call to undeclared function 'snd_pcm_lib_free_vmalloc_buffer'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1411 |             err = snd_pcm_lib_free_vmalloc_buffer(substream);
      |                   ^
/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1857:17: error: use of undeclared identifier 'snd_pcm_lib_get_vmalloc_page'; did you mean 'snd_pcm_lib_malloc_pages'?
 1857 |     .page =     snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
./include/sound/pcm.h:1315:5: note: 'snd_pcm_lib_malloc_pages' declared here
 1315 | int snd_pcm_lib_malloc_pages(struct snd_pcm_substream *substream, size_t size);
      |     ^
/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1857:17: error: incompatible function pointer types initializing 'struct page *(*)(struct snd_pcm_substream *, unsigned long)' with an expression of type 'int (struct snd_pcm_substream *, size_t)' (aka 'int (struct snd_pcm_substream *, unsigned long)') [-Wincompatible-function-pointer-types]
 1857 |     .page =     snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1870:17: error: use of undeclared identifier 'snd_pcm_lib_get_vmalloc_page'; did you mean 'snd_pcm_lib_malloc_pages'?
 1870 |     .page =     snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 snd_pcm_lib_malloc_pages
./include/sound/pcm.h:1315:5: note: 'snd_pcm_lib_malloc_pages' declared here
 1315 | int snd_pcm_lib_malloc_pages(struct snd_pcm_substream *substream, size_t size);
      |     ^
/var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.c:1870:17: error: incompatible function pointer types initializing 'struct page *(*)(struct snd_pcm_substream *, unsigned long)' with an expression of type 'int (struct snd_pcm_substream *, size_t)' (aka 'int (struct snd_pcm_substream *, unsigned long)') [-Wincompatible-function-pointer-types]
 1870 |     .page =     snd_pcm_lib_get_vmalloc_page,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 errors generated.
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build/audio_driver.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/lib/modules/6.12.0-1-audiolinux-rt/build/Makefile:1946: /var/lib/dkms/ravenna-alsa-lkm/r155.61ebb0b/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2</code></pre>

**Comment by bondagit** [comment]
yes, we have to switch to the new managed buffer allocation API, old special vmalloc-specific allocation and page handling were dropped starting from kernel v6.12

**Comment by olm52** [comment]
Not compiling on kernl 6.15.0

`  CC [M]  module_timer.o
module_timer.c:73:2: error: call to undeclared function 'hrtimer_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   73 |         hrtimer_init(&ttimer->timer, which_clock, mode);
      |         ^
module_timer.c:73:2: note: did you mean 'hrtimers_init'?
`

**Comment by olm52** [comment]
This patch will work with 6.14 and 6.15 but probably not for prevous kernels, unless using a kernel version condition:

<pre><code>
--- a/module_timer.c.orig	2025-05-30 12:05:39.333991781 +0200
+++ b/module_timer.c	2025-05-30 12:11:05.755551806 +0200
@@ -70,8 +70,8 @@
 			  enum hrtimer_restart (*function)(struct hrtimer *),
 			  clockid_t which_clock, enum hrtimer_mode mode)
 {
-	hrtimer_init(&ttimer->timer, which_clock, mode);
-	ttimer->timer.function = __hrtimer_tasklet_trampoline;
+       hrtimer_setup(&ttimer->timer, __hrtimer_tasklet_trampoline,
+which_clock, mode);
 	tasklet_init(&ttimer->tasklet, __tasklet_hrtimer_trampoline,
 		     (unsigned long)ttimer);
 	ttimer->function = function;
</code></pre>

**Comment by bondagit** [comment]
can you please try the new branch I have just pushed ? 
If it works for you I will merge it back into aes67-daemon branch.
Thanks

**Comment by olm52** [comment]
Yes it works
