### ISSUE TITLE
I cannot compile on aarch64 - raspberry kernel 6.1.x

### ISSUE THREAD

**Issue by antonellocaroli** [bondagit/ravenna-alsa-lkm#13]
`make -C /media/gpkernel/rpi/kernel/rpi3/kernel-GentooPlayer-ST/lib/modules/6.1.28-GentooPlayer-ST+/build/ M=/media/gpkernel/rpi/ravenna-alsa-lkm/driver modules
  CC [M]  /media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.o
/media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.c: In function ‘CW_netfilter_register_hook’:
/media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.c:64:11: error: implicit declaration of function ‘nf_register_net_hook’ [-Werror=implicit-function-declaration]
   64 |     ret = nf_register_net_hook(&init_net, nfho); //register hook
      |           ^~~~~~~~~~~~~~~~~~~~
/media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.c: In function ‘CW_netfilter_unregister_hook’:
/media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.c:77:5: error: implicit declaration of function ‘nf_unregister_net_hook’; did you mean ‘unregister_netdev’? [-Werror=implicit-function-declaration]
   77 |     nf_unregister_net_hook(&init_net, nfho); //cleanup unregister hook
      |     ^~~~~~~~~~~~~~~~~~~~~~
      |     unregister_netdev
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:250: /media/gpkernel/rpi/ravenna-alsa-lkm/driver/c_wrapper_lib.o] Error 1
make[1]: *** [Makefile:2012: /media/gpkernel/rpi/ravenna-alsa-lkm/driver] Error 2
make: *** [Makefile:15: modules] Error 2
`

**Comment by bondagit** [comment]
Check you kernel config, the following option should be enabled:

> NETFILTER
> HIGH_RES_TIMERS
> NETLINK

**Comment by antonellocaroli** [comment]
if I don't miss anything I'm there 

https://pastebin.com/PsGHDAxS

**Comment by bondagit** [comment]
Check your kernel toolchain. ‘nf_register_net_hook’ is declared in official kernel v6.1.X, at:
`https://github.com/torvalds/linux/blob/v6.1/include/linux/netfilter.h`
in your Kernel config you need to  have CONFIG_NETFILTER.

**Comment by antonellocaroli** [comment]
was my problem
